// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SEARCH_EPXDEMO_H_
#define FLATBUFFERS_GENERATED_SEARCH_EPXDEMO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace epxdemo {

struct SearchRequest;
struct SearchRequestBuilder;

struct SearchResult;
struct SearchResultBuilder;

struct SearchResponse;
struct SearchResponseBuilder;

struct SearchRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SearchRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUERY = 4,
    VT_LIMIT = 6
  };
  const ::flatbuffers::String *query() const {
    return GetPointer<const ::flatbuffers::String *>(VT_QUERY);
  }
  int32_t limit() const {
    return GetField<int32_t>(VT_LIMIT, 10);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_QUERY) &&
           verifier.VerifyString(query()) &&
           VerifyField<int32_t>(verifier, VT_LIMIT, 4) &&
           verifier.EndTable();
  }
};

struct SearchRequestBuilder {
  typedef SearchRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_query(::flatbuffers::Offset<::flatbuffers::String> query) {
    fbb_.AddOffset(SearchRequest::VT_QUERY, query);
  }
  void add_limit(int32_t limit) {
    fbb_.AddElement<int32_t>(SearchRequest::VT_LIMIT, limit, 10);
  }
  explicit SearchRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SearchRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SearchRequest>(end);
    fbb_.Required(o, SearchRequest::VT_QUERY);
    return o;
  }
};

inline ::flatbuffers::Offset<SearchRequest> CreateSearchRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> query = 0,
    int32_t limit = 10) {
  SearchRequestBuilder builder_(_fbb);
  builder_.add_limit(limit);
  builder_.add_query(query);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SearchRequest> CreateSearchRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *query = nullptr,
    int32_t limit = 10) {
  auto query__ = query ? _fbb.CreateString(query) : 0;
  return epxdemo::CreateSearchRequest(
      _fbb,
      query__,
      limit);
}

struct SearchResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SearchResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TITLE = 4,
    VT_SCORE = 6
  };
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  float score() const {
    return GetField<float>(VT_SCORE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyField<float>(verifier, VT_SCORE, 4) &&
           verifier.EndTable();
  }
};

struct SearchResultBuilder {
  typedef SearchResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(SearchResult::VT_TITLE, title);
  }
  void add_score(float score) {
    fbb_.AddElement<float>(SearchResult::VT_SCORE, score, 0.0f);
  }
  explicit SearchResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SearchResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SearchResult>(end);
    fbb_.Required(o, SearchResult::VT_TITLE);
    return o;
  }
};

inline ::flatbuffers::Offset<SearchResult> CreateSearchResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    float score = 0.0f) {
  SearchResultBuilder builder_(_fbb);
  builder_.add_score(score);
  builder_.add_title(title);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SearchResult> CreateSearchResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *title = nullptr,
    float score = 0.0f) {
  auto title__ = title ? _fbb.CreateString(title) : 0;
  return epxdemo::CreateSearchResult(
      _fbb,
      title__,
      score);
}

struct SearchResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SearchResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<epxdemo::SearchResult>> *results() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<epxdemo::SearchResult>> *>(VT_RESULTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RESULTS) &&
           verifier.VerifyVector(results()) &&
           verifier.VerifyVectorOfTables(results()) &&
           verifier.EndTable();
  }
};

struct SearchResponseBuilder {
  typedef SearchResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_results(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<epxdemo::SearchResult>>> results) {
    fbb_.AddOffset(SearchResponse::VT_RESULTS, results);
  }
  explicit SearchResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SearchResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SearchResponse>(end);
    fbb_.Required(o, SearchResponse::VT_RESULTS);
    return o;
  }
};

inline ::flatbuffers::Offset<SearchResponse> CreateSearchResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<epxdemo::SearchResult>>> results = 0) {
  SearchResponseBuilder builder_(_fbb);
  builder_.add_results(results);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SearchResponse> CreateSearchResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<epxdemo::SearchResult>> *results = nullptr) {
  auto results__ = results ? _fbb.CreateVector<::flatbuffers::Offset<epxdemo::SearchResult>>(*results) : 0;
  return epxdemo::CreateSearchResponse(
      _fbb,
      results__);
}

inline const epxdemo::SearchRequest *GetSearchRequest(const void *buf) {
  return ::flatbuffers::GetRoot<epxdemo::SearchRequest>(buf);
}

inline const epxdemo::SearchRequest *GetSizePrefixedSearchRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<epxdemo::SearchRequest>(buf);
}

template <bool B = false>
inline bool VerifySearchRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<epxdemo::SearchRequest>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedSearchRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<epxdemo::SearchRequest>(nullptr);
}

inline void FinishSearchRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<epxdemo::SearchRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSearchRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<epxdemo::SearchRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace epxdemo

#endif  // FLATBUFFERS_GENERATED_SEARCH_EPXDEMO_H_
