# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epxdemo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SearchResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SearchResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSearchResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SearchResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SearchResponse
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from epxdemo.SearchResult import SearchResult
            obj = SearchResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SearchResponse
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SearchResponse
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SearchResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    SearchResponseStart(builder)

def SearchResponseAddResults(builder, results):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)

def AddResults(builder, results):
    SearchResponseAddResults(builder, results)

def SearchResponseStartResultsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartResultsVector(builder, numElems):
    return SearchResponseStartResultsVector(builder, numElems)

def SearchResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return SearchResponseEnd(builder)

import epxdemo.SearchResult
try:
    from typing import List
except:
    pass

class SearchResponseT(object):

    # SearchResponseT
    def __init__(
        self,
        results = None,
    ):
        self.results = results  # type: Optional[List[epxdemo.SearchResult.SearchResultT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        searchResponse = SearchResponse()
        searchResponse.Init(buf, pos)
        return cls.InitFromObj(searchResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, searchResponse):
        x = SearchResponseT()
        x._UnPack(searchResponse)
        return x

    # SearchResponseT
    def _UnPack(self, searchResponse):
        if searchResponse is None:
            return
        if not searchResponse.ResultsIsNone():
            self.results = []
            for i in range(searchResponse.ResultsLength()):
                if searchResponse.Results(i) is None:
                    self.results.append(None)
                else:
                    searchResult_ = epxdemo.SearchResult.SearchResultT.InitFromObj(searchResponse.Results(i))
                    self.results.append(searchResult_)

    # SearchResponseT
    def Pack(self, builder):
        if self.results is not None:
            resultslist = []
            for i in range(len(self.results)):
                resultslist.append(self.results[i].Pack(builder))
            SearchResponseStartResultsVector(builder, len(self.results))
            for i in reversed(range(len(self.results))):
                builder.PrependUOffsetTRelative(resultslist[i])
            results = builder.EndVector()
        SearchResponseStart(builder)
        if self.results is not None:
            SearchResponseAddResults(builder, results)
        searchResponse = SearchResponseEnd(builder)
        return searchResponse
