# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epxdemo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SearchResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SearchResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSearchResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SearchResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SearchResult
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SearchResult
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SearchResultStart(builder):
    builder.StartObject(2)

def Start(builder):
    SearchResultStart(builder)

def SearchResultAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    SearchResultAddTitle(builder, title)

def SearchResultAddScore(builder, score):
    builder.PrependFloat32Slot(1, score, 0.0)

def AddScore(builder, score):
    SearchResultAddScore(builder, score)

def SearchResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return SearchResultEnd(builder)


class SearchResultT(object):

    # SearchResultT
    def __init__(
        self,
        title = None,
        score = 0.0,
    ):
        self.title = title  # type: Optional[str]
        self.score = score  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        searchResult = SearchResult()
        searchResult.Init(buf, pos)
        return cls.InitFromObj(searchResult)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, searchResult):
        x = SearchResultT()
        x._UnPack(searchResult)
        return x

    # SearchResultT
    def _UnPack(self, searchResult):
        if searchResult is None:
            return
        self.title = searchResult.Title()
        self.score = searchResult.Score()

    # SearchResultT
    def Pack(self, builder):
        if self.title is not None:
            title = builder.CreateString(self.title)
        SearchResultStart(builder)
        if self.title is not None:
            SearchResultAddTitle(builder, title)
        SearchResultAddScore(builder, self.score)
        searchResult = SearchResultEnd(builder)
        return searchResult
