# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epxdemo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SearchRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SearchRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSearchRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SearchRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SearchRequest
    def Query(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SearchRequest
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 10

def SearchRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    SearchRequestStart(builder)

def SearchRequestAddQuery(builder, query):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)

def AddQuery(builder, query):
    SearchRequestAddQuery(builder, query)

def SearchRequestAddLimit(builder, limit):
    builder.PrependInt32Slot(1, limit, 10)

def AddLimit(builder, limit):
    SearchRequestAddLimit(builder, limit)

def SearchRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SearchRequestEnd(builder)


class SearchRequestT(object):

    # SearchRequestT
    def __init__(
        self,
        query = None,
        limit = 10,
    ):
        self.query = query  # type: Optional[str]
        self.limit = limit  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        searchRequest = SearchRequest()
        searchRequest.Init(buf, pos)
        return cls.InitFromObj(searchRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, searchRequest):
        x = SearchRequestT()
        x._UnPack(searchRequest)
        return x

    # SearchRequestT
    def _UnPack(self, searchRequest):
        if searchRequest is None:
            return
        self.query = searchRequest.Query()
        self.limit = searchRequest.Limit()

    # SearchRequestT
    def Pack(self, builder):
        if self.query is not None:
            query = builder.CreateString(self.query)
        SearchRequestStart(builder)
        if self.query is not None:
            SearchRequestAddQuery(builder, query)
        SearchRequestAddLimit(builder, self.limit)
        searchRequest = SearchRequestEnd(builder)
        return searchRequest
